import Link from "next/link";
import "./globals.css";
import Counter from "@/components/Counter";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import "../node_modules/@fortawesome/fontawesome-free/css/all.min.css"

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
